version: '2'
services:
    frontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        ports:
            - "41001:9000"
    backend:
        build:
          context: ./backend
          dockerfile: Dockerfile
        ports:
          - "41002:8100"
    mongodb:
        image: mongo
        ports:
          - "41003:27017"