version: '2'
services:
    frontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile.local
        ports:
            - "41001:9000"
        volumes:
          - ./frontend:/src
    backend:
        build:
          context: ./backend
          dockerfile: Dockerfile.local
        ports:
          - "41002:8100"
        volumes:
          - ./backend:/src