version: '2'
services:
    customer-ui-backend:
        build:
          context: .
          dockerfile: Dockerfile.local
        ports:
            - "41001:8100"
        volumes:
          - .:/src
        environment:
          EVENTSTORE_TYPE: 'mongodb'
          EVENTSTORE_HOST: 'mongodb'
          EVENTSTORE_PORT: '27017'
          RABBITMQ_ENDPOINT: 'amqp://rabbitmq:5672'
          LOG_LEVEL: 'trace'
        depends_on:
          - rabbitmq
          - mongodb
    rabbitmq:
        image: rabbitmq:3-management
        ports:
          - "41002:5672"
          - "41003:15672"
    mongodb:
        image: mongo
        ports:
          - "41004:27017"
